# Generated by Django 3.1.3 on 2020-12-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201222_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
