# Generated by Django 3.1.3 on 2020-12-22 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_auto_20201222_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(related_name='my_group_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
